import {
  Home01Icon,
  SparklesIcon,
  Activity02Icon,
  Clock01Icon,
  DocumentCodeIcon,
  Calendar03Icon,
  Notification02Icon,
  UserCircleIcon,
  SecurityCheckIcon,
  AiBrain01Icon,
  Sun01Icon,
  Moon02Icon,
  ComputerIcon,
  Add01Icon,
  Search01Icon,
  AlertCircleIcon,
  HelpCircleIcon,
  DropletIcon,
  HeartCheckIcon,
  WeightScaleIcon,
  Medicine01Icon,
} from "@hugeicons/core-free-icons";

export const ICON_MAP = {
  dashboard: Home01Icon,
  assessment: SparklesIcon,
  tracking: Activity02Icon,
  history: Clock01Icon,
  reports: DocumentCodeIcon,
  consultations: Calendar03Icon,
  notifications: Notification02Icon,
  profile: UserCircleIcon,
  security: SecurityCheckIcon,
  assistant: AiBrain01Icon,
  sun: Sun01Icon,
  moon: Moon02Icon,
  system: ComputerIcon,
  add: Add01Icon,
  search: Search01Icon,
  alert: AlertCircleIcon,
  help: HelpCircleIcon,
  glucose: DropletIcon,
  bloodPressure: HeartCheckIcon,
  weight: WeightScaleIcon,
  insulin: Medicine01Icon,
} as const;
