param([Parameter(Mandatory=$true)][string]$SourceDirectory,[Parameter(Mandatory=$true)][string]$OutputDirectory)
$ErrorActionPreference='Stop'
$icons=[ordered]@{
'Home01Icon'='ic_huge_home_24';'Activity01Icon'='ic_huge_activity_24';'TaskDone01Icon'='ic_huge_assessment_24';'BubbleChatIcon'='ic_huge_message_24';'MoreHorizontalIcon'='ic_huge_more_horizontal_24';'TimeQuarterPassIcon'='ic_huge_history_24';'Clock01Icon'='ic_huge_clock_24';'File02Icon'='ic_huge_report_24';'Calendar03Icon'='ic_huge_calendar_24';'Notification02Icon'='ic_huge_notification_24';'UserIcon'='ic_huge_user_24';'ArrowLeft02Icon'='ic_huge_arrow_left_24';'Cancel01Icon'='ic_huge_close_24';'Add01Icon'='ic_huge_add_24';'Edit02Icon'='ic_huge_edit_24';'Delete02Icon'='ic_huge_delete_24';'Search01Icon'='ic_huge_search_24';'FilterIcon'='ic_huge_filter_24';'Upload01Icon'='ic_huge_upload_24';'Download01Icon'='ic_huge_download_24';'Share01Icon'='ic_huge_share_24';'RefreshIcon'='ic_huge_refresh_24';'ArrowRight01Icon'='ic_huge_chevron_right_24';'ArrowDown01Icon'='ic_huge_chevron_down_24';'InformationCircleIcon'='ic_huge_info_24';'Alert02Icon'='ic_huge_warning_24';'Tick02Icon'='ic_huge_check_24';'LockIcon'='ic_huge_lock_24';'SecurityCheckIcon'='ic_huge_shield_24';'WifiDisconnected01Icon'='ic_huge_offline_24';'DocumentAttachmentIcon'='ic_huge_document_24';'ChartUpIcon'='ic_huge_trend_24'
}
New-Item -ItemType Directory -Path $OutputDirectory -Force|Out-Null
$directional=@('ArrowLeft02Icon','ArrowRight01Icon')
foreach($entry in $icons.GetEnumerator()){
 $sourcePath=Join-Path $SourceDirectory ($entry.Key+'.js');if(-not(Test-Path -LiteralPath $sourcePath)){throw "Missing pinned Hugeicons source: $($entry.Key)"}
 $source=Get-Content -LiteralPath $sourcePath -Raw;$elements=[regex]::Matches($source,'\["([^"]+)",\s*\{([^}]+)\}\]');if($elements.Count -eq 0){throw "No geometry found in $($entry.Key)"}
 $paths=[System.Collections.Generic.List[string]]::new()
 foreach($element in $elements){$type=$element.Groups[1].Value;$body=$element.Groups[2].Value;if($type -eq 'path'){$d=[regex]::Match($body,'d:\s*"([^"]+)"').Groups[1].Value}elseif($type -eq 'circle'){$cx=[double]([regex]::Match($body,'cx:\s*"([^"]+)"').Groups[1].Value);$cy=[double]([regex]::Match($body,'cy:\s*"([^"]+)"').Groups[1].Value);$r=[double]([regex]::Match($body,'r:\s*"([^"]+)"').Groups[1].Value);$d="M$($cx-$r),$cy A$r,$r 0,1 0,$($cx+$r),$cy A$r,$r 0,1 0,$($cx-$r),$cy"}else{throw "Unsupported SVG element '$type' in $($entry.Key); conversion requires review."};if([string]::IsNullOrWhiteSpace($d)){throw "Missing geometry in $($entry.Key)"};$width=[regex]::Match($body,'strokeWidth:\s*"([^"]+)"').Groups[1].Value;if($width -ne '1.5'){throw "Unexpected stroke width '$width' in $($entry.Key)"};$escaped=[System.Security.SecurityElement]::Escape($d);$paths.Add("    <path android:pathData=`"$escaped`" android:fillColor=`"@android:color/transparent`" android:strokeColor=`"@color/care_ink`" android:strokeWidth=`"1.5`" android:strokeLineCap=`"round`" android:strokeLineJoin=`"round`" />")}
 $mirror=if($directional -contains $entry.Key){' android:autoMirrored="true"'}else{''};$lines=[System.Collections.Generic.List[string]]::new();$lines.Add('<?xml version="1.0" encoding="utf-8"?>');$lines.Add("<vector xmlns:android=`"http://schemas.android.com/apk/res/android`" android:width=`"24dp`" android:height=`"24dp`" android:viewportWidth=`"24`" android:viewportHeight=`"24`"$mirror>");$lines.AddRange($paths);$lines.Add('</vector>');$xml=$lines-join[Environment]::NewLine;$outputPath=Join-Path $OutputDirectory ($entry.Value+'.xml');[System.IO.File]::WriteAllText($outputPath,$xml+[Environment]::NewLine,[System.Text.UTF8Encoding]::new($false))
}
Write-Output "Converted and validated $($icons.Count) MIT Hugeicons Stroke Rounded assets."
